### PR TITLE
Add cinder get_pools interface for getting volume backend storage info

### PR DESCRIPTION
**Pull request by gf-chen40**
#762 
Author: chenguofeng
Email：gf.chen40@gmail.com

Add support of the following RESTful API:
GET/v2/​{tenant_id}​/scheduler-stats/get_pools
GET/v2/​{tenant_id}​/scheduler-stats/get_pools?detail=True

### CODE REVIEW

**Comment by gf-chen40** [comment]
@auhlig Sorry to take a long time to commit this feature. I finally fixed my compile environment and get the code right on the master branch.

**Comment by auhlig** [comment]
@gf-chen40 Cool. Could you resolve the conflicts?

**Comment by gf-chen40** [comment]
Hi @auhlig how to see the conflicts ? I cant see any conflicts here. Also it said "Only those with write access to this repository can merge pull requests".

**Comment by auhlig** [comment]
@gf-chen40 you need to update your branch by merging containx:master in your gf-chen40:master.

**Comment by auhlig** [comment]
I guess besides that it looks good.
Or did I miss something @vinodborole ?

**Comment by vinodborole** [comment]
@gf-chen40  can you please resolve the conflicts?

Step 1: From your project repository, check out a new branch and test the changes.

git checkout -b gf-chen40-master master
git pull https://github.com/gf-chen40/openstack4j.git master
Step 2: Merge the changes and update on GitHub.

git checkout master
git merge --no-ff gf-chen40-master
git push origin master

**Comment by vinodborole** [comment]
@gf-chen40 please resolve conflicts so that we can take this further

**Comment by gf-chen40** [comment]
Sorry to take a long time.
New PR#782 should be ok

**Pull request closed without merging**
