### PR TITLE
Implement close method in the okhttp HttpResponseImpl to avoid leak

### LINKED ISSUE #855: The okhttp HttpResponseImpl do not implement the close method
I want know why the okhttp HttpResponseImpl close method do nothing.
In my project show this log.
okhttp3.internal.platform.Platform log
warn: A connection to http://10.110.20.131:8774/ was leaked. Did you forget to close a response body?
Shoud I call this.response.body().close(); in the close method

### PR DESCRIPTION
**Pull request by jcoste-orange**
Fix #855

### CODE REVIEW

**Comment by vinodborole** [comment]
Thanks a lot @jcoste-orange. LGTM, what do you think @auhlig ?

**Comment by auhlig** [comment]
Nitpicking: We could have saved a couple of characters as `response.body().close();` and `response.close();` are equivalent. 

I guess it's good to merge the way it is now. Thanks @jcoste-orange.

**Comment by jcoste-orange** [comment]
There's no method close on class okhttp3.Response. So @auhlig I don't understand your comment.

**Comment by auhlig** [comment]
True. I looked at a newer version of the api. Sorry.

**Pull request merged**
