### PR TITLE
Group based Policy feature implementation

### PR DESCRIPTION
**Pull request by vinodborole**
OpenStack Group-Based Policy (GBP) framework, designed to offer a new set of abstraction that allows to manage OpenStack infrastructure through declarative policy abstractions. It provides declarative abstractions for achieving scalable intent-based infrastructure automation.

### CODE REVIEW

**Comment by gondor** [comment]
@vinodborole Really, really good work!  This will fit right in with the direction of the library.

Couple minor things:

- Any reason the Enums you defined can't follow the rest of the APIs conventions (UpperCase constants).  For example the Protocol and Direction enum.  You can use the ```@JsonCreated``` and ```@JsonValue``` to handle lowercase to/from serialization.  We have done this with most enums.

- Can we get at least a few tests added.  This is really handy on releases and other contributors making changes knowing they haven't broken this work.  It adds quality to the library as well and allows us to test future JSON responses from future versions of OpenStack.

Overall, thats really all I can comment on, great job!

**Comment by vinodborole** [comment]
@gondor Thanks a lot for the kind words jeremy. I will make sure to make the changes suggested and will include tests in my next PR.

Again, appreciate you taking out time and looking at this PR.

**Comment by vinodborole** [comment]
@gondor  i have added the test cases and changes you suggested. However, when i test the test cases i get NullPointer exception for OSClient; i am not sure if there is anything more i have to do. Can you please verify that?

**Comment by vinodborole** [comment]
@gondor  Is it good enough to be merged?

**Comment by gondor** [comment]
@vinodborole It looks good but since I didn't handle essentially any of the V3 release I want to give Arno and Darren a chance to look this over.  They are in Germany so opposite time zones.  If there's no feedback by tomorrow morning, I'll merge this and cut a SNAPSHOT.  We're trying to quickly get a 3.0.1 release out containing the Builder mod so this PR is in time to also make the release.

**Comment by vinodborole** [comment]
@gondor  Thanks Jeremy. :+1:

**Comment by auhlig** [comment]
Hey @vinodborole,
Just had a quick look.
Are org.openstack4j.api.gbp.ServicechainService and -NetworkService supposed to be empty? 

Would also be happy to see someone else using the groovy tests ;)

Apart from that it looks good.

**Comment by vinodborole** [comment]
@auhlig yes they are empty for now. I will adding the implementation in a week or so, as for now these are not used hence the delay

**Comment by vinodborole** [comment]
@auhlig @gondor please let me know if there is anything more i need to add to this to make it a candidate for merge.

**Comment by gondor** [comment]
LGTM - As @auhlig it would be nice to transfer over to the groovy tests.  Maybe your next PR you can try the groovy tests.  Feel free to reach out to Arno if you have questions for the groovy based tests.   

Going wait a bit to see if Arno has any additional comments

**Comment by auhlig** [comment]
LGTM.

Sure I can with the groovy tests. But as Jeremy said that is definitely something for another PR.

**Comment by vinodborole** [comment]
@auhlig  Do share some of the sample tests already written for reference and i can have them written on priority.

**Comment by gondor** [comment]
Merged and Snapshot deployed

**Comment by vinodborole** [comment]
@gondor  Thanks a lot jeremy

**Comment by auhlig** [comment]
@vinodborole: There are groovy tests for the Identity V3 part in the core-integration module. The shortest one is https://github.com/ContainX/openstack4j/blob/master/core-integration-test/src/test/groovy/org/openstack4j/api/identity/v3/KeystoneTokenServiceSpec.groovy .

Maybe as a short intro:
It's written in groovy, using [spock test framework] (https://code.google.com/archive/p/spock/) and [betamax] (http://betamax.software/) to record client-server communication and replay later.
That reminds me of updating https://github.com/ContainX/openstack4j/blob/master/core-integration-test/README.md .

**Comment by vinodborole** [comment]
@auhlig thanks will have a look and update test cases accordingly

**Pull request merged**
