### PR TITLE
Added implementation for ceilometer sample

### PR DESCRIPTION
**Pull request by sjpatil**
Earlier there was support for samples listed from meter service only " /v2/meters/​{meter_name}​".
Added implementation for sample service and APIs to support sample operation related to it "/v2/samples" and "/v2/samples/{sample_id}"
There is discrepancy in responses of APIs mentioned in openstack API docs for meter service samples as they are shown same as sample service samples but actually they are different.
This will support in part for issue #701

### CODE REVIEW

**Comment by vinodborole** [comment]
@sjpatil 
please fix the errors

**Comment by vinodborole** [comment]
@sjpatil  Fix your test cases please

**Comment by sjpatil** [comment]
@auhlig  My build is failing in jersey2 connector integration tests , can you help here?

**Comment by auhlig** [comment]
Short answer: It fails only with jdk1.8. That's not related to your work. There's still an issue with jdk1.8 and the integration-tests.

Longer answer: The current problem is the integration of the recent version of betamax. After being distracted from that I'm now looking into solving that. So far betamax is not easy to debug -.-

**Comment by vinodborole** [comment]
LGTM @gondor and @auhlig  can you guyz review?

**Comment by auhlig** [comment]
LGTM

**Comment by gondor** [comment]
LGTM, thanks for being patient

**Pull request merged**
