### PR TITLE
fix  Firewall policy param cannot be updated

### PR DESCRIPTION
**Pull request by scsunchen**
fix  Firewall policy param cannot be updated #1068

### CODE REVIEW

**Comment by auhlig** [comment]
Hi @scsunchen, 
I'm very sorry this PR didn't get attention so far. 
I was looking at https://developer.openstack.org/api-ref/networking/v2/index.html?expanded=create-firewall-group-detail,id284-detail#id284 and didn't see the `firewall_policy_id` attribute. Looks like that was a thing in v1. 
In v2 this was replaced by `egress_firewall_policy_id` and `ingress_firewall_policy_id`.
AFAIK, OpenStack4j currently supports only networking v1 and v2 only if there was no change, but I'm not to familiar with this part. Maybe you are?

**Comment by scsunchen** [comment]
@auhlig that is in v1.   It's a bug .

**Comment by auhlig** [comment]
Both v1 and v2 point to /v2/-paths? Probably the docs are incorrect on the path here.
In v1 I can still see`firewall_policy_id` as a valid parameter in both request and response of the update method https://developer.openstack.org/api-ref/networking/v2/index.html?expanded=create-firewall-group-detail,id284-detail,update-firewall-rule-detail#update-firewall-rule. Which version of the networking version are you using @scsunchen?

**Comment by scsunchen** [comment]
@auhlig  
when I use `os.networking().firewalls().firewall() .update()`   。`ClientResponseException{message=Unrecognized attribute(s) 'policy', status=400, status-code=BAD_REQUEST}`
`firewall_policy_id` is a valid. but `policy `is a invalid 
please look at the NeutronFirewallUpdate.java . 79 line.


{
"firewall" : {
 "shared" : false,
 "**policy**" : "036ab1f1-271e-4db1-8d04-e4ed226924c8",
 "admin_state_up" : true,
 "firewall_policy_id" : "036ab1f1-271e-4db1-8d04-e4ed226924c8"
 }
}
It has not been validated

[https://developer.openstack.org/api-ref/networking/v2/?expanded=update-firewall-detail#extensions](url)

**Comment by auhlig** [comment]
What do you think on this @vinodborole?

**Comment by vinodborole** [comment]
@auhlig @scsunchen After referring to the documentation for v2 i believe the parameter "policy" does not exists. So it makes sense to ignore it.

**Comment by auhlig** [comment]
Since we're currently not distinguishing between v1 and v2. There just one networking service for both we're lucky they don't seem to differ much. I was concerned, as I thought merging this could break things for v1, where the policy attribute exists. Makes sense @vinodborole @scsunchen ?

**Comment by scsunchen** [comment]
@vinodborole I agree with you。But look at the file : https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewallUpdate.java   in 78 line number . Where's @JsonIgnore?  
why not have a try it ?

and  look https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/openstack/networking/domain/ext/NeutronFirewall.java
in  135 line .

**Comment by scsunchen** [comment]
如果还不能证明我是对的。那么我放弃提交这个更新！

**Comment by auhlig** [comment]
What do you think @vinodborole?

**Comment by vinodborole** [comment]
@auhlig I think it makes perfect sense to ignore the "policy" property in neutronFirewall Update as the get firewall has ignored it.

**Comment by auhlig** [comment]
Thanks @scsunchen!

**Pull request merged**
