### PR TITLE
#654: Retrive password for a server

### PR DESCRIPTION
**Pull request by vinodborole**
API /v2.1/​{tenant_id}​/servers/​{server_id}​/os-server-password can get Admin password

OR CLI nova get-password {server_id}

### CODE REVIEW

**Comment by gondor** [comment]
@vinodborole could you check the branch conflicts

**Comment by vinodborole** [comment]
@gondor  done, please check

**Comment by gschukin** [comment]
@vinodborole any chance to have method that will accept InputStream pointing to ssh key to have password decrypted? Or maybe a utility method?

**Comment by Dolimont** [comment]
@vinodborole Indeed, it would helps a lot to have such method

**Comment by vinodborole** [comment]
@gschukin good idea, i have opened a new ticket #1005 and added as enhancement will add it soon.

**Pull request merged**
