### PR TITLE
Fix #673: Bring back Java 7 support

### LINKED ISSUE #673: JKD1.7
my project is JDK1.7，How can i use openstack4j 3.0.0?

### PR DESCRIPTION
**Pull request by olivergondza**
- Project depends on 1.7
- Controllers affected by [JDK-7157360](https://bugs.openjdk.java.net/browse/JDK-7157360) depends on 1.8
- `distribution` module depends on `openstack4j-resteasy`

### CODE REVIEW

**Comment by olivergondza** [comment]
I managed to get the build to pass on JDK 7 using `mvn clean install -pl '!org.pacesys.openstack4j.connectors:openstack4j-http-connector,!org.pacesys.openstack4j.connectors:openstack4j-jersey2,!org.pacesys:it-jersey2'` (skipping affected controllers). Except for integration tests that does not work for me with Java 8 either.

**Comment by gondor** [comment]
@auhlig and @dhague can you review this

**Comment by dhague** [comment]
LGTM - nice work!

**Comment by gondor** [comment]
@dhague @olivergondza @auhlig 

for some reason Travis which runs "mvn test -B" passes but trying to deploy which goes through "mvn verify" fails.   I was trying to cut a release this morning.   Can someone find out why some groovy tests are failing using "mvn verify" ?  If not we'll have to revert this change.

Common error seen:
```
Running org.openstack4j.api.identity.v3.KeystoneProjectServiceSpec
Jun 01, 2016 7:05:48 AM org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoCachedMethodSiteNoUnwrap invoke
INFO: local address is loopback, using hostname C02Q41AMG8WM-M.local
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.121 sec <<< FAILURE! - in org.openstack4j.api.identity.v3.KeystoneProjectServiceSpec
create, read, update, delete project service test cases(org.openstack4j.api.identity.v3.KeystoneProjectServiceSpec)  Time elapsed: 0.12 sec  <<< ERROR!
java.lang.AbstractMethodError: javax.ws.rs.core.UriBuilder.uri(Ljava/lang/String;)Ljavax/ws/rs/core/UriBuilder;
	at org.openstack4j.api.identity.v3.KeystoneProjectServiceSpec.create, read, update, delete project service test cases(KeystoneProjectServiceSpec.groovy:77)
```

**Comment by auhlig** [comment]
I guess ```mvn test``` runs only the unit tests. But the integration-tests are only executed in the integration-phase which is a previous phase of verify.

**Comment by gondor** [comment]
Ok, gonna update travis to always test using "mvn verify"

**Comment by auhlig** [comment]
Yes. Sorry. Should have thought of that before.

**Pull request merged**
