### PR TITLE
Add Neutron agent-list

### PR DESCRIPTION
**Pull request by biogerm**
Neutron agent-list function was supported.
This change is contributed by Yin Zhang, Magnus Broman, Qin An
(@biogerm)

### CODE REVIEW

**Comment by auhlig** [comment]
LGTM

**Comment by vinodborole** [comment]
LGTM

**Comment by gondor** [comment]
@biogerm Once you fix the merge conflicts we will merge this.

**Comment by biogerm** [comment]
Just fixed the conflicts but.. emm.. this is new. Seems got access denied in Travis?

**Comment by biogerm** [comment]
Is there any way to restart CI build? Was it a glitch that maven failed to download its plugin?

**Comment by auhlig** [comment]
@biogerm Maybe. Close & Reopen PR will trigger travis build.

**Comment by biogerm** [comment]
@auhlig that's the weird part because that was what I did on the last commit - solve the conflicts xD
Maybe I've done something wrong. Anyways, I pushed another PR and that one should be fine. Please close this PR.

**Pull request closed without merging**
