### PR TITLE
Adding limit to SampleCriteria for Ceilometer APIs

### PR DESCRIPTION
**Pull request by pdube**

### CODE REVIEW

**Comment by auhlig** [comment]
Could you add a brief test / modify the existing one? 
LGTM besides.

**Comment by vinodborole** [comment]
LGTM, tests would be good.

**Comment by pdube** [comment]
I will push the tests soon

**Comment by pdube** [comment]
Hey guys, I pushed a couple tests. Could you take a quick look? Thanks

**Comment by vinodborole** [comment]
LGTM

**Comment by pdube** [comment]
Thanks!

**Pull request merged**
