### PR TITLE
Allow value to be object type in ServiceConfig

### PR DESCRIPTION
**Pull request by ekasitk**
This PR allows values in ServiceConfig to be an integer or any other types than just a string. So the generated JSON is correctly formatted according to the type of value.

### CODE REVIEW

**Comment by vinodborole** [comment]
@ekasitk can you please share the use case for this change request?

**Comment by ekasitk** [comment]
When setting service parameters, values can be string or number.

      ServiceConfig hdfsConf = Builders.serviceConfig()
                                  .set("dfs.namenode.logging.level","info")
                                  .set("dfs.replication",1);
     Cluster cluster = Builders.cluster().name("test")
                            .addServiceConfig("HDFS",hdfsConf);

This PR permits ServiceConfig.set() to accept number and  generate the json like:
{
  "name" : "test",
  "cluster_configs" : {
    "HDFS" : {
      "dfs.namenode.logging.level" : "info",
      "dfs.replication" : 1
    }
  },
  "hadoop_version" : "1.6.2"
}

Otherwise, all values will always be treated as string, i.e. "dfs.replication" : "1", which is not  complied well to the API.  Ref: https://developer.openstack.org/api-ref/data-processing/?expanded=show-details-of-a-cluster-detail.

**Comment by auhlig** [comment]
Makes sense. Or not @vinodborole?

**Comment by vinodborole** [comment]
I agree @auhlig as per the openstack doc this change request makes sense. A test for a more complex config will be necessary in order to be sure nothing else breaks. @ekasitk is it possible for you to add this test case along with this PR?

**Comment by ekasitk** [comment]
@vinodborole  @auhlig  
I can add some test cases but it will take a while.

**Comment by vinodborole** [comment]
@ekasitk sure not a problem

**Comment by ekasitk** [comment]
@vinodborole @auhlig 
I've added some test cases for this PR. Please kindly check.

**Comment by vinodborole** [comment]
LGTM @auhlig what do you think?

**Comment by auhlig** [comment]
LGTM. Many thanks @ekasitk

**Pull request merged**
