### PR TITLE
Add missing api for cinder

### PR DESCRIPTION
**Pull request by biogerm**
This change was originally committed by Elina Meier (elina.meier@ericsson.com).
The commit was modified and adapted to openstack4j 3.x by Qin An

In this commit, VolumeType was supported.

### CODE REVIEW

**Comment by vinodborole** [comment]
Thanks @biogerm  for the contribution, looks good. It would be good if you can add few units test around this?

**Comment by biogerm** [comment]
@vinodborole I actually removed the tests which are wrote based on openstack4j 1.x
I will see what I can do

**Comment by auhlig** [comment]
Any reason for changing the import pattern in the Builders?

**Comment by biogerm** [comment]
@auhlig Thanks for pointing out. I guess it was because of the merge between really old code. And I realized that the other comment I was suppose to sent was not sent... Here it goes...

**Comment by biogerm** [comment]
Hi Community,

We work in Ericsson and has been using and improving Openstack4j for 2 years. Only until recently did we get the permit to contribute our changes back to Github, and we are so happy about it.

I am currently working on modifying and upstreaming these changes here. These changes are in general working fine with us for a long time. I will group them in several pull requests that I hope they won't dependent on each other.

BR
Qin An

**Comment by vinodborole** [comment]
@biogerm we would really like to have those changes; please do send those PR and we can look at it.

Thanks again for your contribution!

**Comment by gondor** [comment]
@biogerm Awesome! looking forward to the contributions

**Comment by biogerm** [comment]
@vinodborole Test is now included. Just wondering if I should send it as another pull request or it's fine to have two commits?
@gondor Thanks

**Comment by biogerm** [comment]
things are breaking.. i'm on it..

**Comment by auhlig** [comment]
LGTM

**Comment by gondor** [comment]
@vinodborole awaiting your final review.  Merge if it looks good

**Comment by vinodborole** [comment]
apologies for the delay, LGTM

**Pull request merged**
