### PR TITLE
Added API for Octavia

### PR DESCRIPTION
**Pull request by Grim-lock**
octavia API has some difference from neutron lbaas API, so create a separate directory, and I will add L7 API later.

### CODE REVIEW

**Comment by auhlig** [comment]
That was a lot of work. Many thanks @Grim-lock!
Although this looks very promising could you add tests?

**Comment by Grim-lock** [comment]
@auhlig I would like to do it, but I can not know how much time is spent, maybe 2 weeks or 3 weeks.

**Comment by Grim-lock** [comment]
@auhlig finished the test case

**Comment by auhlig** [comment]
Perfect @Grim-lock! Many thank. Good to merge from my side.
What do you think @vinodborole ?

**Comment by vinodborole** [comment]
@Grim-lock  many thanks. LGTM

**Pull request merged**
