### PR TITLE
Added a new method createSnapshot() to invoke create image action API with metadata properties

### PR DESCRIPTION
**Pull request by cbirajdar**
Openstack API to [create image](https://developer.openstack.org/api-ref/compute/?expanded=create-image-createimage-action-detail#create-image-createimage-action) allows passing optional metadata properties. Overloaded `createSnapshot()` to handle additional metadata and maintain backwards compatibility.

### CODE REVIEW

**Comment by vinodborole** [comment]
@cbirajdar thanks for this, it would really be good if we have some tests around this new method. Also, what if metadata is not null but empty; whats the behaviour of the API call?

**Comment by cbirajdar** [comment]
Added unit tests for the new method. @vinodborole @auhlig Please review and merge when you get a chance. Thanks!

**Comment by vinodborole** [comment]
LGTM, thanks @cbirajdar 👍

**Comment by cbirajdar** [comment]
Thanks @vinodborole! Can this be merged now?

**Pull request merged**
