### PR TITLE
Murano API: implementing deployments

### PR DESCRIPTION
**Pull request by nmakhotkin**
* Added deployment service API
* Now it is possible to query the deployment log
of the environment
* Added corresponding unit-tests

### CODE REVIEW

**Comment by auhlig** [comment]
@nmakhotkin  Ready for review?

**Comment by nmakhotkin** [comment]
@auhlig yes, here is only one commit this time :)

**Comment by auhlig** [comment]
Looks very good 👍  Thanks @nmakhotkin.
What do you think @vinodborole ?

**Comment by vinodborole** [comment]
same here @auhlig :+1:  LGTM

**Comment by nmakhotkin** [comment]
Thank you guys!

**Pull request merged**
