### PR TITLE
support ipv6 properties in subnet

### PR DESCRIPTION
**Pull request by taemin77**
Hi, I'm Taemin.
I added two ipv6 properties for creating and getting subnet.

- ipv6_address_mode
  : The IPv6 address modes specifies mechanisms for assigning IP addresses. Value is slaac, dhcpv6-stateful, dhcpv6-stateless or null.
- ipv6_ra_mode
 : The IPv6 router advertisement specifies whether the networking service should transmit ICMPv6 packets, for a subnet. Value is slaac, dhcpv6-stateful, dhcpv6-stateless or null.

### CODE REVIEW

**Comment by auhlig** [comment]
Hi @taemin77,
Thanks for the work.

Any objections from your side @vinodborole on changing method signature of [NeutronSubnetNoGateway](https://github.com/ContainX/openstack4j/pull/964/commits/fe7413cd33cb09d57041722ee0b7ef3f108fa10f#diff-49c36d9c62da61933065647b90eae2acR242) and [NeutronSubnet](https://github.com/ContainX/openstack4j/pull/964/commits/fe7413cd33cb09d57041722ee0b7ef3f108fa10f#diff-49c36d9c62da61933065647b90eae2acR64)?

**Comment by vinodborole** [comment]
All good, just added one comment on formatting

**Comment by taemin77** [comment]
merged commit ?

**Comment by taemin77** [comment]
Hi, 
I added Block Storage Service List API.
I wanted to create "new pull request", but I could't seem to do it because previous pull request didn't finish.

**Comment by auhlig** [comment]
HI @taemin77, the previous PR wasn't merged yet.
Could you address @vinodborole's comment first?

You can push the changes for the block storage to a new branch and create a PR from there.
Would prefer this in the future to not mix up the PRs.

**Comment by taemin77** [comment]
Hi,
Where can I find @vinodborole 's comment?
Could you let me know how to check comment?
I will create new branch about block storage.
Thank you.

**Comment by auhlig** [comment]
Ah. Right. Can't see it too. Didn't you comment @vinodborole?

**Comment by auhlig** [comment]
@taemin77 Could you revert to https://github.com/ContainX/openstack4j/pull/964/commits/fe7413cd33cb09d57041722ee0b7ef3f108fa10f so we don't mix things up here and you already created a separate PR for the block storage commits?

**Comment by taemin77** [comment]
Ok, I did it.

**Comment by vinodborole** [comment]
LGTM

**Comment by taemin77** [comment]
??

**Comment by auhlig** [comment]
Many thanks for contributing @taemin77

**Comment by taemin77** [comment]
@auhlig  I have question.
"openstack4j-3.0.4-20170316.085041-28-sources.jar" don't have subent ipv6 propertise.
Didn't subnet ipv6  include in SNAPSHOT yet?

**Comment by auhlig** [comment]
It should be in the latest snapshot.

**Pull request merged**
