### PR TITLE
Closing input stream, ref#622

### PR DESCRIPTION
**Pull request by vinodborole**
public static long copy(InputStream from,
        OutputStream to)
                 throws IOException
Copies all bytes from the input stream to the output stream. **Does not close or flush either stream**.

### CODE REVIEW

**Comment by vinodborole** [comment]
@auhlig Can you please review this request?

**Comment by gschukin** [comment]
Why not to use try-with-resource since we're on 1.8 anyway?

**Comment by vinodborole** [comment]
@gschukin thanks; that was a good suggestion. I have modified the PR with the change

**Comment by gschukin** [comment]
Why not both streams?
I'm OOO so not able to comment properly :-(

**Comment by vinodborole** [comment]
@gschukin thanks again, made the change.

**Comment by gschukin** [comment]
So why not to stick to Outputstream interface? 

I'm preparing a big pr with findbugs and etc changes with all that small fixes. ;-)

**Comment by vinodborole** [comment]
@gschukin that is really great! please let me know if i can be of any help in building that PR

**Pull request merged**
