### PR TITLE
fix failing integration-tests

### PR DESCRIPTION
**Pull request by auhlig**
Hi,
As mentioned in #707,
this should do the trick to fix the integration-test failures at least for JDK 1.7 .

### CODE REVIEW

**Comment by auhlig** [comment]
Looks the script in the travis.yml, which should skip test for connectors affected by the jdk1.7-bug didn't work - although it works locally.

**Comment by olivergondza** [comment]
It seems to skip the `script` instruction altogether and always run `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V`.

**Comment by auhlig** [comment]
Yes. I'm not sure why the instruction works locally but is ignored by travis.

**Comment by gondor** [comment]
Let me try updating the master .travis with these changes.  I have a feeling travis is looking at masters.

**Comment by olivergondza** [comment]
This seems to be the cause: https://docs.travis-ci.com/user/languages/java#Dependency-Management-with-Default-install

**Comment by auhlig** [comment]
closing this, because of #710

**Pull request closed without merging**
