### PR TITLE
Issue 903 remove last route

### PR DESCRIPTION
**Pull request by silvanstrueby**
Bugfix for issue #903.

### CODE REVIEW

**Comment by auhlig** [comment]
Many Thanks @silvanstrueby.
Could you add a short test to verify your fix works?

**Comment by silvanstrueby** [comment]
Hi @auhlig 

I tried to implement a test but I'm afraid to say that unfortunately it would take me too long to write reasonable tests. Because I'm not familiar with your test setup and I couldn't find any existing tests for the RouterService to get some inspiration.

The fix itself compared to the effort I would need to test it is disproportionally in my opinion.
I know it doesn't really help you, but we use this fix in our productive system and it solved the problem.

I hope you can understand my point of view?

**Comment by auhlig** [comment]
Mh. What do you think on this @vinodborole?

**Comment by vinodborole** [comment]
@auhlig should not be a problem LGTM

**Pull request merged**
