### PR TITLE
Adding support of interface of cinder get_pools.

### PR DESCRIPTION
**Pull request by gf-chen40**
#762 
Author: chenguofeng
Email：gf.chen40@gmail.com

Add support of the following RESTful API:
**GET/v2/​{tenant_id}​/scheduler-stats/get_pools
GET/v2/​{tenant_id}​/scheduler-stats/get_pools?detail=True**

### CODE REVIEW

**Comment by auhlig** [comment]
@gf-chen40 LGTM. I would be happy if you could at least a short test.

**Comment by auhlig** [comment]
@gf-chen40 Thanks for the test cases. Can you check on the errors and resolve them?

**Comment by gf-chen40** [comment]
@auhlig So sorry for making such error. Should be ok now.
Let me know if any problems.
Thanks;-)

**Comment by auhlig** [comment]
@gf-chen40 My fault. Didn't see you where already on it :) LGTM.

Would it be much work to get this in master?

**Comment by gf-chen40** [comment]
@auhlig I think it also work in master. Just merge the codes to master and no more changes. BTW Is there any problems in master that I can't compile in my local environment.

**Comment by auhlig** [comment]
@gf-chen40 Build looks green. Can you share some details?

**Comment by gf-chen40** [comment]
what detail do you need?

**Comment by auhlig** [comment]
Where is it failing on your side?

**Comment by gf-chen40** [comment]
@auhlig Sorry to take a long time to commit this feature. I finally fixed my compile environment and get the code right on the master branch.
#774

**Comment by auhlig** [comment]
@gf-chen40 Meaning this PR can be closed in favor of #774?

**Pull request closed without merging**
