### PR TITLE
Implemented all CRUD operations for Openstack SFC

### PR DESCRIPTION
**Pull request by maxrome**
The new code allow to create, update, delete and list the following SFC objects:

- Port Pair
- Port Pair Group
- Flow Classifier
- Port Chain

For details see the official documentation:
[https://docs.openstack.org/newton/networking-guide/config-sfc.html](https://docs.openstack.org/newton/networking-guide/config-sfc.html)
[https://docs.openstack.org/networking-sfc/latest/contributor/api.html](https://docs.openstack.org/networking-sfc/latest/contributor/api.html)

Massimiliano

### CODE REVIEW

**Comment by auhlig** [comment]
Thanks for all the work @maxrome.
Could you add a reasonable set of (unit-)tests for this?

**Comment by maxrome** [comment]
Hello @auhlig , I hadn't enough time to implement also the unit tests, but the code was tested directly on a Red Hat Openstack 11 installation (Ocata) using another java project. Of course I will write also the unit test, but for now I have to move to other tasks. If you have an Openstack with SFC fetures enabled, I could send you the code to test all CRUD operations. Let me know

**Comment by auhlig** [comment]
@maxrome Unfortunately we don't have the time for a detailed review and extensive test of this huge amount of changes, so please add some unit or integration tests.

**Comment by arvindn05** [comment]
@auhlig #1141 addresses the same. I think this pull request can be closed provided the other one is merged.

**Comment by vinodborole** [comment]
@arvindn05 please close this PR if not required

**Pull request closed without merging**
