### PR TITLE
Fix cpu info in hypervisor

### PR DESCRIPTION
**Pull request by zizhongwei**
Fix cpu info in hypervisor for #1012

### CODE REVIEW

**Comment by auhlig** [comment]
Hi @zizhongwei,
Thanks for the PR.
Could you wrap some test around that? Why are you using `List<Object>`?

**Comment by zizhongwei** [comment]
there is a note in the openstack api description:
```Since version 2.28 cpu_info field is returned as a dictionary instead of string.```
When I use the Hypervisor list api to get the hypervisors,it returned a JSON like this：
``` {Source: {"model": ["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"], "vendor": ["GenuineIntel"], "nodes": 1, "topology": {"cores": 12, "threads": 24}}}```
in this JSON, "model" field is ```["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"]``` and "vendor" field is ```["GenuineIntel"]```.
In my test the Jackson can reads this "model" field to ```List<Object>```
and the Jackson can also reads JSON ```"model": "Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"``` to ```List<Object>```，
so I replaced ```String``` with ```List<Object>```

**Comment by auhlig** [comment]
Wouldn't​ `List<Object>` be incompatible with the jsom-string, whereas the type string would work for both?

**Comment by zizhongwei** [comment]
openstack4j has used Jackson read json to java Object. Jackson can read json-string :```"model": "Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"``` to ```List<Object>```, also can read json :```"model": ["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"]``` to  ```List<Object>```; Jackson can not read json :```"model": ["Intel(R)Xeon(R)CPUE5-2620v2@2.10GHz"]``` to  ```String```  : #1012

**Comment by auhlig** [comment]
I see. LGTM. Thanks @zizhongwei

**Pull request merged**
