### PR TITLE
Fix get console output not working with Resteasy connector (#795)

### PR DESCRIPTION
**Pull request by lorenzo-biava**
This PR replaces the JSON String encoding of the compute.getConsoleOutput API request with a standard `EntityModel `so that it fixes issue #795.

With this entity modification, it also changes the default console length, which is now the full console instead of 50 lines.

Some unit tests has been added for this API.

### CODE REVIEW

**Comment by lorenzo-biava** [comment]
@auhlig It's ready for me. Let me know if there's anything that needs improvement...

**Comment by auhlig** [comment]
Thanks for all the work @lorenzo-biava.
Could you explain the need for the `takeRequest()` method in AbstractTest?
It works without and if necessary, you can always use `server.takeRequest()` in the respective test classes that extend AbstractTest.
Besides this looks good.

**Comment by lorenzo-biava** [comment]
Sure. I wanted to make sure that the console output lenght logic was correct and so I needed to check the request for the `length` parameter presence/absence.
So I added a common `takeRequest()` method for a couple of reasons, even though it is not absolutely necessary.

The first is that I thought that an abstraction on the mock server like `respondWith()` would be more consistent (and perhaps the `takeRequest()` method might have additional logic in the future).

The second, more practical one, is that in the `createServer` test there's already a variable named `server`, so it would clash with the mock server field.

I can change the variable in the `createServer()` method or use `this.server.takeRequest()` if you prefer, but i felt it would be less confusing having a dedicated common method to access common mock server functionalities indirectly.

**Comment by auhlig** [comment]
Makes sense. Thanks @lorenzo-biava. Merging now.

**Pull request merged**
