### PR TITLE
Include the EndpointURLResolver in the services defined in the

### PR DESCRIPTION
**Pull request by bcornelis**
Include the EndpointURLResolver in the services defined in the
APIProvider. This allows for easy extending/overriding of the default
EndpointURLResolver logic.

### CODE REVIEW

**Comment by auhlig** [comment]
Hi @bcornelis,
Thanks for contributing.
Is there an issue with the current way the EndpointResolver can be used/overridden? Could you share how your proposal would make it easier?
Also should that really live in apiprovider? What's your opinion @vinodborole, @gondor ?

**Comment by bcornelis** [comment]
Dear @auhlig ,
the problem for me is that, as far as I can see, it's impossible to change the logic of the EndpointURLResolver. This one is instantiated in the OSClientSession class, and does not have any getters/setters. So how is it possible in the current situation, to provide a custom implementation?
As 'all' other services are defined in the Apis class, I thought it would be most application-compliant way to also use this logic to specify which implementation to use.

**Comment by auhlig** [comment]
Currently it can be done the following way https://github.com/ContainX/openstack4j/issues/390

**Comment by bcornelis** [comment]
Thanks for your explanation and sample, but this is not what I need. My usecase is that I need the identity V3, but the endpoint URL is not the same as the one returned in the tokens catalog. I Don't need the URL from the catalog, but the one specified in token.endpoint.

I think it's not possible to achieve this with the ServiceVersionResolver mentioned in the ticket #390, as for the V3 URL resolution, this resolver isn't even used. The only location where this ServiceVersionResolver is used, is to resolve the V2 (DefaultEndpointURLResolver::resolveV2). The resolveV3 is never used.

So in my case I've extended the DefaultEndpointURLResolver by always returning the tokens endpoint for the Identity service, and fallback to the default resolution (based on the catalog) for other services. As this class is instantiated like 'EndpointURLResolver epr = new DefaultEndpointURLResolver();' in the OSClientSession class, it seemed for me impossible to extend it.

What's your opinion on this?

**Comment by auhlig** [comment]
Right. It's not the purpose of the endpoint resolver as, per default, OpenStack services get their respective endpoint from the token catalog. 
Just to make sure: Does defining a custom resolver
```
final ServiceVersionResolver resolver = new ServiceVersionResolver() {
    @Override
    public Service resolve(ServiceType type, SortedSet<? extends Service> services) {
        // resolver logic; possibly ext. default logic
        return endpoint;
    }
};
```
and overriding standard behavior with `.withConfig(Config.newConfig().withResolver(resolver))` while building the OSClient not work?

**Comment by bcornelis** [comment]
This doesn't do the trick for me. Problem is really that the Openstack installation I'm connecting to has identity V2 exposed in the endpoints, but the V3 is available, but not listed in the endpoints. So I always get the V2 where the V3 is available. So if I choose V3 authentication, V2 is always chosen as this is the one included in the token.
Extending the ServiceVersionResolver won't do the trick, as this class is only used in the code for the V2 resolution, but I'm using V3.

**Comment by vinodborole** [comment]
@bcornelis  "Problem is really that the Openstack installation I'm connecting to has identity V2 exposed in the endpoints, but the V3 is available, but not listed in the endpoints" - I think a better way to deal with this is you fix your openstack rather than a workaround over this.

**Comment by auhlig** [comment]
I completely agree with @vinodborole.

Although we should think about the resolver. It should be easier to override.

**Comment by bcornelis** [comment]
I definitely agree with  @vinodborole and @auhlig that properly configuring the Openstack installation should be the first thing to do, but unfortunately, it's configured by external companies, so it's not an option for now.
Besides that I share the same reasoning as @auhlig that anyway the library currently doesn't allow for any modification to this class, which can be improved.
@auhlig: can you agree to solve this by 1) using the API's to expose the service or 2) include it in the Config class? I can update the patch to match your decision.
Thanks!

**Comment by auhlig** [comment]
I'd rather go for the config option. If you already have something in mind: Could you share an example of how it would be used @bcornelis ?

**Comment by bcornelis** [comment]
It would be used like `.withConfig(Config.newConfig().withEndpointURLResolver(resolver))`.

**Comment by auhlig** [comment]
Ah even better if that patter remains. Looking forward to the updated commit. Could you also add a short test for that? Thanks in advance for your work. Feel free to reach out in case you need help.

**Comment by bcornelis** [comment]
done! Please let me know what you think about it.

**Comment by auhlig** [comment]
Very cool @bcornelis. What's your opinion @vinodborole?

**Comment by vinodborole** [comment]
LGTM, a documentation around this will help a lot, @bcornelis  can you also update the doc on the website at these places

http://openstack4j.com/learn/identity/identity-v2/#services-and-endpoints

http://openstack4j.com/learn/identity/identity-v3/#services-and-endpoints

what do you think @auhlig ?

**Comment by auhlig** [comment]
Good idea @vinodborole. 
Since this is not specific to idv2/v3 I was thinking of a short section in http://openstack4j.com/learn/getting-started guide explaining  config options. Maybe @bcornelis can start with the new resolver and I volunteer to complete this. Makes sense?

We now have the old `.withResolver(resolver)` and the new `.withEndpointURLResolver(resolver))`. Mark the old as deprecated or replace with the new option? Or would there still be a use-case for this?

**Comment by bcornelis** [comment]
@auhlig,
I suggest to leave the withResolver logic as it allows for easy changing the ServiceVersionResolver. Although, I suggest to rename it to something like `.withServiceVersionResolver(resolver)`.

I'll provide you with an initial version of the getting started documentation for this addition. Can you please give me a hint how/where to update documentation? Or I just send you my suggestion and you'll incorporate it?

**Comment by auhlig** [comment]
Sounds good.
Regarding the docs: I'll prepare a section for the config options during the day and notify you when it's done.

**Comment by bcornelis** [comment]
@auhlig Were you already able to prepare the docs? Thanks!

**Comment by auhlig** [comment]
Thanks for the reminder and sorry for the delay.
No pushing in the evening. Will do it tomorrow morning.

**Comment by auhlig** [comment]
@bcornelis Maybe you can mention the endpoint resolver here https://github.com/ContainX/openstack4j.com/commit/76448629369fad41aa82c55f10b087bb57a254e3#diff-2158f2689ed69342e8755af3e6844928R243 ?

**Comment by auhlig** [comment]
**push** @vinodborole @bcornelis

**Comment by vinodborole** [comment]
@auhlig i guess we should do it as part of another PR, better for tracking that way.

**Comment by auhlig** [comment]
Makes sense. Then I guess this one can be merged.

**Pull request merged**
