### PR TITLE
Trove

### PR DESCRIPTION
**Pull request by sumit74**
Adding implementation for trove instance, datastore, database, database user and flavor APIs.

### CODE REVIEW

**Comment by vinodborole** [comment]
@sumit74 @sjpatil  please resolve the conflicts

**Comment by sumit74** [comment]
Resolved the conflicts.

**Comment by vinodborole** [comment]
LGTM 

@gondor @auhlig can you guyz please have a look?

**Comment by gondor** [comment]
LGTM, thanks for the contribution

**Comment by auhlig** [comment]
👍 LGTM

**Pull request merged**
