### PR TITLE
Support for Tacker  - NFV Orchestration - Version 1.0 Implementation

### PR DESCRIPTION
**Pull request by vishvesh**
#### This PR adds support for Tacker  - NFV Orchestration - Version 1.0 Implementation
Please review and merge the initial `API Implementation` for **`Tacker - NFV Orchestration`**.. 
`Links to the Docs:` 
* https://wiki.openstack.org/wiki/Tacker
* http://docs.openstack.org/developer/tacker/devref/mano_api.html
* https://github.com/openstack/tacker/blob/master/doc/source/devref/mano_api.rst

#### Below are the Commit Descriptions:
* Tacker - Initial API Definition..
 * Added initial `Tacker API` Definitions..
* Tacker - Added Tacker Builders and Interfaces..
 * Added `Tacker Builders` and `Interfaces` for the following:
  * `VNF Catalog`
  * `VNF Manager`
  * `VIM Management`
* Tacker - Added API Implementation and Domain Classes..
 * Completed `Tacker Domain and Internal` class implementation
 * TODO: `VIM - Update` API is pending, everything else is implemented and Tested..
* Tacker - Added binding in DefaultAPIProvider..
 * Added `binding` in `DefaultAPIProvider` class..
* Tacker - Exposed Tacker Service APIs via OSClient & OSClientSession..
 * `Tacker` Services are now exposed via `OSClient` and `OSClientSession`..
* **`Note:`** 
 * `VIM Update API` is yet to be implemented..
 * I have not added any `Test Cases` for the same, but I have tested and written tests on my `Client`.. I am not sure if the contributions are accepted only with `Test` validations?
 * Also note that `Tacker APIs` are still `under development` and not yet part of the `Official Documentation`.. So they `might change` in the future.. Since we are using it already, I thought of contributing so someone interested can use and enhance them..
 * I have created an Issue to `Track Tacker Related` Implementation issues : https://github.com/ContainX/openstack4j/issues/786

#### Below are the API Usages:
* **Tacker `VNFD API`**:
```java
/** VNFD List */
List<? extends Vnfd> vnfds = os.tacker().vnfd().list();

/** VNFD Get by ID */
Vnfd vnfd = os.tacker().vnfd().get(v.getId());

/** VNFD Create */
VnfdAttributes attributes = VnfdAttributes.create().vnfd(vnfdTemplate);
VnfdServiceTypes serviceTypes = VnfdServiceTypes.create().serviceType("vnfd");
List<VnfdServiceTypes> serviceTypesList = Lists.newArrayList(serviceTypes);
Vnfd vnfd = Builders.tacker().vnfd()
	.name("Vnfd-Test")
	.description("VNFD-Test-Description")
	.infrastructureDriver("heat")
	.managementDriver("noop")
	.attributes(attributes)
	.serviceTypes(serviceTypesList)
	.build();
Vnfd newVnfd = os.tacker().vnfd().create(vnfd);

/** VNFD Delete */
ActionResponse res = os.tacker().vnfd().delete(newVnfd.getId());
```
* **Tacker `VNF API`**:
```java
/** VNF List */
List<? extends Vnf> vnfs = os.tacker().vnf().list();

/** VNF Get by ID */
Vnf vnf = os.tacker().vnf().get(v.getId());

/** VNF Create */
Vnf vnf = Builders.tacker().vnf()
		.name("VNF-Test")
		.description("VNF-Test-Description")
		.vnfdId("0f6b23aa-d27e-4104-821f-2f62c4bf4f91")
		.build();
Vnf newVnf = os.tacker().vnf().create(vnf);

/** VNF Update */
/** Before Updating, Poll for the VNF Status to be TackerVnfStatus.ACTIVE and then Execute the following:*/
String vnfUpdateConfig = "vdus:\n  vdu1:\n    id: vdu1\n    vm_image: cirros-0.3.4-x86_64-uec\n    instance_type: m1.tiny\n\n    network_interfaces:\n      management:\n        network: net_mgmt\n        management: true\n      pkt_in:\n        network: net0\n      pkt_out:\n        network: net1\n\n    placement_policy:\n      availability_zone: nova\n\n    auto-scaling: noop\n\n";
VnfUpdateAttributes vnfUpdateAttributes = VnfUpdateAttributes.create().config(vnfUpdateConfig);
VnfUpdate vnfUpdate = Builders.tacker().vnfUpdate().attributes(vnfUpdateAttributes).build();
Vnf updatedVnf = os.tacker().vnf().update(pollVnf.getId(), vnfUpdate);

/** VNF Delete */
ActionResponse res = os.tacker().vnf().delete(updatedVnf.getId())
```
* **Tacker `VIM API`**:
```java
/** VIM List */
List<? extends Vim> vims = os.tacker().vim().list();

/** VIM Show by ID */
Vnfd vim = os.tacker().vim().show(v.getId());

/** VIM Register */
VimProject vimProject = VimProject.create().name("admin").projectDomainName("default");
AuthCredentials authCredentials = AuthCredentials.create()
		.username("admin")
		.password("password")
		.userDomainName("default");
Vim vim = Builders.tacker().vim()
		.name("VIM-Test")
		.description("VIM-Test-Description")
		.authUrl("http://OpenStack-IP:35357/v3")
		.isDefault(Boolean.FALSE)
		.type("openstack")
		.vimProject(vimProject)
		.authCredentials(authCredentials)
		.build();
vim = os.tacker().vim().register(vim);

/** VIM Delete */
ActionResponse res = os.tacker().vim().delete(vim.getId());
```

### CODE REVIEW

**Comment by vinodborole** [comment]
@vishvesh good stuff. LGTM

@gondor @auhlig

**Comment by auhlig** [comment]
Wow. Many thanks @vishvesh .
I'll take some time tomorrow to review.

**Comment by auhlig** [comment]
Looks very good.

**Comment by gondor** [comment]
@vishvesh Really, really good stuff!  I agree with @auhlig .  Could we get some tests for this.

**Comment by vishvesh** [comment]
@gondor @auhlig @vinodborole : Thanks! I will try to write and contribute tests once I am free.. I have tested and using all these functions in my Application, and having no troubles so far.

Will this be merged, or should I add more commits to this `PR` with `tests`?

**Comment by auhlig** [comment]
As this PR is introducing so much new stuff I'd be happy to have some basic tests here before merging.

**Comment by auhlig** [comment]
Feel free to reach out in case you need help :)

**Comment by vishvesh** [comment]
@auhlig : Ohh that would be awesome :+1: I'll try to add some tests by next weekend..

**Comment by vishvesh** [comment]
@auhlig , am I missing some configuration for executing Tests?

I have added `Tacker` in `Service` Enum in `AbstractTest` class..
```java
protected enum Service {
    IDENTITY(5000), 
    NETWORK(9696), 
    COMPUTE(8774), 
    BLOCK_STORAGE(8776), 
    METERING(8087), 
    TELEMETRY(8087), 
    SHARE(8786), 
    OBJECT_STORAGE(8800),
    CLUSTERING(8778),
    TACKER(9890)
    ;
```

When I try to run my `Tacker` Test class, I get the following error:
```
testListVnfds(org.openstack4j.api.tacker.v1.TackerVnfdTests)  Time elapsed: 1.056 sec  <<< FAILURE!
org.openstack4j.api.exceptions.ConnectionException: java.net.ConnectException: Connection refused: connect

Failed tests: 
  TackerVnfdTests.testListVnfds:34 » Connection java.net.ConnectException: Conne...

Tests run: 343, Failures: 1, Errors: 0, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenStack4j Connectors ............................. SUCCESS [  0.843 s]
[INFO] OpenStack4j Jersey2 Connector ...................... FAILURE [ 14.948 s]
[INFO] OpenStack4j RestEasy Connector ..................... SKIPPED
```

I am running `mvn clean install` on `openstack4j-core-tests` for building, and same maven command on `openstack4j-connectors` to execute the test cases.. Is this the right way? I don't remember executing tests in such a way for `Firewall Service Tests`..

**Comment by auhlig** [comment]
You're on the right track.
Looking at the short test in https://github.com/ContainX/openstack4j/blob/master/core-test/src/main/java/org/openstack4j/api/identity/v3/KeystonePolicyServiceTest.java in addition you would need to something like 
```
@Override
    protected Service service() {
        return Service.TACKER;
    }
```
and then mock each call with ```respondWith(<json-mock>); ```

**Comment by vishvesh** [comment]
@auhlig : Other tests (Neutron, Compute, etc.) pass, so the `MockWebServer` definitely starts..

Usually the exception will say that the port is already in use, but it is not already used..

Not sure what's going on.. I looked for any other missing configuration for new Service (Port) in Test, but it could not find any other config, all I did is added the below code, and the `Tacker Por 9890`..
```java
@Override
protected Service service() {
    return Service.TACKER;
}
```

Btw, is there a way I run only my `Test` cases? Or I have to run `mvn clean install` on the `openstack4j-connectors` module?

**Comment by auhlig** [comment]
Ah. Right. 
BTW: Running either ```mvn clean test``` for tests in core-test module or ```mvn clean verify``` including integration tests (if you added some) in project root should the trick.

**Comment by vishvesh** [comment]
Doesn't work for me :( I am doing `mvn clean test` on `openstack4j-connectors`..

**Comment by auhlig** [comment]
Maybe it fails, because the java version of the connectors are different. Some req. Java 7, some Java 8. Take a look at https://github.com/ContainX/openstack4j/blob/master/.travis.yml#L23-L24. See skipped modules in line 8.

**Comment by vishvesh** [comment]
That's fine, I am able to run tests via `openstack4j-connectors`..

**Comment by gondor** [comment]
@vishvesh let us know when your ready for final review.  Also we'll need branch conflicts resolved

**Comment by vishvesh** [comment]
@gondor : Sure, will try to find time this week, and let you know..

Regarding the conflicts, it doesn't show me what's conflicting since I do not have write access to the repository..

**Comment by auhlig** [comment]
@vishvesh You don't need write access to the repo. You could do it the other way around and merge the latest into your branch.

**Comment by vishvesh** [comment]
@auhlig : Okay.. :+1:

**Comment by vishvesh** [comment]
@gondor @auhlig : 

Merge conflicts `resolved` :+1: 
All `Tacker` Tests are now complete :+1: 

Please review and merge this PR..

**Comment by vinodborole** [comment]
LGTM @gondor @auhlig your take please

**Comment by auhlig** [comment]
Very nice @vishvesh. 👍

**Comment by auhlig** [comment]
I'm hesitating to merge since https://travis-ci.org/ContainX/openstack4j/builds/159561585 failed. What are we going to do about it? @vinodborole @gondor

**Comment by gondor** [comment]
@auhlig looking at the files on this one it looks like the underlying import that was missing in the previously failure was added to this one.  Travis is saying this PR is passing so I think we're good to merge

**Comment by auhlig** [comment]
Hi Jeremy, Right. Sounds good. Merging now.

**Comment by vishvesh** [comment]
@gondor @vinodborole @auhlig : Awesome.. Thanks :+1:

**Comment by auhlig** [comment]
Hey @vishvesh, 
Just wondered if we have some kind of documentation for the this service in os4j? Else could you add some for our website https://github.com/containx/openstack4j.com. It's just markdown.

**Comment by vishvesh** [comment]
@auhlig : Alright 👍 I will contribute the Documentation for Os4j Website. Although, I am not sure about the timeline for my contribution for the mark-down..

`Tacker Documentation` mentioned here:
* https://wiki.openstack.org/wiki/Tacker

Will try to make it similar to this:
* https://github.com/ContainX/openstack4j.com/blob/master/learn/network/networks-fwaas.md

**Comment by auhlig** [comment]
That would be awesome @vishvesh. Many thanks in advance. 
Feel free to reach out to me in case you need help.

**Pull request merged**
