### PR TITLE
Mistral client: workflow definitions

### PR DESCRIPTION
**Pull request by rakhmerov**
* Added stubs for all API services and models
* Fully implemented workflow definitions service

Next steps:
* Implement other services

### CODE REVIEW

**Comment by vinodborole** [comment]
Thank you for the contribution @rakhmerov It would be good if you can add some documentation around this

**Comment by rakhmerov** [comment]
@vinodborole Hi, can you please clarify what kind of documentation you're expecting? More detailed PR message or something else? If you mean mean the official docs for Mistral part, I was planning to do that once I finish the implementation. Anyway, I'm new here and it'd be good if you could point me where I should be looking.

Thanks,
Renat

**Comment by vinodborole** [comment]
@rakhmerov Sure; you can look at this for example - http://openstack4j.com/learn

We can add an entry for Mistral here and follow the same format as other. You can fork the repo https://github.com/ContainX/openstack4j.com and add your changes in https://github.com/ContainX/openstack4j.com/tree/master/learn section.

**Comment by rakhmerov** [comment]
@vinodborole Ok, thanks. I'll do that. Is it ok to do it after client APIs implementation?

**Comment by vinodborole** [comment]
@rakhmerov Sure; thanks a lot for your contribution

**Comment by rakhmerov** [comment]
Hi. Can you review this PR again please?

**Comment by rakhmerov** [comment]
@vinodborole Hi, do I need to do anything else so that this PR is reviewed? I also more patches to be sent but am not doing this for now till this PR is approved.

**Comment by vinodborole** [comment]
@rakhmerov Sorry for the delay was caught up. Your PR LGTM. @auhlig  what do you think?

**Comment by rakhmerov** [comment]
OK, thanks ) I'm planning to finish the entire Mistral part within a couple of weeks (would do it faster but I have only one day a week for this workstream).

**Comment by auhlig** [comment]
Had a quick look. It's good to merge. 
Looking forward to your next PR @rakhmerov :)

**Comment by rakhmerov** [comment]
Thanks!

**Pull request merged**
