### PR TITLE
Mistral: add task and action execution endpoints

### PR DESCRIPTION
**Pull request by rakhmerov**
* Added all needed entities to implement Mistral task execution endpoint

### CODE REVIEW

**Comment by rakhmerov** [comment]
@vinodborole Hi. Please review this PR when you have a chance.

**Comment by vinodborole** [comment]
LGTM

**Comment by rakhmerov** [comment]
@vinodborole Thanks!

Btw, a quick question:  who is in charge of approving PRs in this repo? Is it worth reaching out to certain people to move things faster? Or I just need to wait?

Kindly asking for clarity )

Renat

**Comment by vinodborole** [comment]
@rakhmerov Usually its me and @auhlig look after the contributions, but either of us can take decision to merge depending upon how busy each one of us is. 
Between, i just merged it :)

Thanks again for the contributions @rakhmerov

**Comment by rakhmerov** [comment]
@vinodborole Ooh, wonderful! Thanks for merging it :) More commits are on their way..

**Pull request merged**
