### PR TITLE
use Long insead of Integer in class GlanceImage

### PR DESCRIPTION
**Pull request by whaon**
fix issue:  #875

### CODE REVIEW

**Comment by whaon** [comment]
@auhlig ,hi,I've submit serveral issues and a PR,please help me to check it,thanks

**Comment by auhlig** [comment]
Hey @whaon, @tongh-qtl,
Thanks for the work. 
I'm wondering if this is actually causing problems as the API specifically mentions integer for the properties you're referring to: http://developer.openstack.org/api-ref/image/v2/?expanded=show-image-details-detail#show-image-details

**Comment by whaon** [comment]
yes,it is **definitely** can cause a problem,consider  the introduction of the field size:
```
size	body	integer	The size of the image data, in bytes. The value might be null (JSON null data type).
```
the unit is in **bytes**,so the value may be two long
our system get a problem yesterday,so I think it is a potential problem to others
I think the integer in the doc is just indicate that this field is a nonnegative number,but the size may be huge,and it is not the concept of Interger in Java,thank you!

**Comment by auhlig** [comment]
I don't have a strong opinion here. Besides my previous comment - maybe I misinterpreted integer in the docs - I would be fine with this change. What do you think @vinodborole?

**Comment by vinodborole** [comment]
same thought @auhlig I am not sure, what do you think @gondor ?

**Comment by whaon** [comment]
the unit is in bytes
```
/**
     * A constant holding the maximum value an {@code int} can
     * have, 2<sup>31</sup>-1.
     */
    public static final int   MAX_VALUE = 0x7fffffff;
```
as above,the Integer.MAX_VALUE is 2147483647
2147483647**bytes** / 1024 / 1024 /1024 = 1.999999999068677425384521484375**G**
so the size of an Image can be as large as 2GB
but in actural,many Image can be more than 2GB

**Comment by vinodborole** [comment]
@whaon the change is valid no doubt about that. Will need a final confirmation from @gondor on this as this will not be backward compatible, people using the older version will have an impact on their exiting code when they port to new version.

**Comment by whaon** [comment]
@vinodborole It's OK

**Comment by gondor** [comment]
@vinodborole @auhlig Should we consider cutting a new release first (soon) before this merge since there is a lot of changes already in the release.   Then we could have a smaller quicker follow on release with a few fixes and changes.  It would be easier to see the breaking changes this way.   Thoughts?

**Comment by auhlig** [comment]
@gondor Since murano service in os4j  is unfortunately not making progress I guess it's the right time. So +1 for os4j 3.0.3

**Comment by whaon** [comment]
@auhlig @vinodborole @gondor 
hi,may I close this PR and reopen it after the release 3.0.3,because there are another two issues need be fixed: #878 #877

**Comment by vinodborole** [comment]
@gondor I completely agree!

**Comment by whaon** [comment]
close temporarily

**Comment by whaon** [comment]
how about this issue now?Guys

**Comment by vinodborole** [comment]
@whaon will you be able to take this now?

**Comment by vinodborole** [comment]
reference to #875 

@auhlig can you please review this pull request?

**Comment by auhlig** [comment]
Good to merge from my side 👍

**Pull request merged**
