### PR TITLE
Addition of Glance image V2

### PR DESCRIPTION
**Pull request by emjburns**
https://github.com/ContainX/openstack4j/issues/647
Documentation PR here: https://github.com/ContainX/openstack4j.com/pull/12

@gondor @vinodborole please take a look

### CODE REVIEW

**Comment by drmaas** [comment]
LGTM

**Comment by vinodborole** [comment]
Awesome! LGTM 

@gondor  @auhlig please have a look

**Comment by auhlig** [comment]
@emjburns Very nice work. Could you resolve the conflicts?

**Comment by emjburns** [comment]
@auhlig resolved!

**Pull request merged**
