### PR TITLE
fix unscoped token authentication

### LINKED ISSUE #1065: NullPointer exception when use only token authentication
Hi All,

I got NullPointer exception when used token authentication w/o specifying the scope like:

OSClientV3 os = OSFactory.builderV3()
                  .endpoint("http://127.0.0.1:5000/v3")
                  .token("{token}"
                  .authenticate();

Looks like exception occurs in 206 line within OSAuthenticator.java,
may it be caused because domain was not specified ?

Thanks,

### PR DESCRIPTION
**Pull request by auhlig**
fixes #1065

### CODE REVIEW

**Comment by auhlig** [comment]
Can you take a look @vinodborole, vkochan?

**Comment by vkochan** [comment]
The null-pointer issue is gone, but I can't query the resources, let me put more details:
OSFactory.enableHttpLoggingFilter(true);
		
		Identifier domainId = Identifier.byName("xxx");
		
		OSClientV3 os = OSFactory.builderV3()
				            .endpoint("http://106.125.46.127:5000/v3")
				            .credentials("xxx", "xxx", domainId)
				            .scopeToProject(Identifier.byName("xxx"), Identifier.byName("xxx"))
				            .authenticate();
		
		OSClientV3 os2 = OSFactory.builderV3()
		                    .endpoint("http://106.125.46.127:5000/v3")
		                    .token(os.getToken().getId())
		                    .authenticate();

		List <? extends Vnf> vnfs = os2.tacker().vnf().list();
		for (Vnf vnf : vnfs) {
            System.out.println("vnf=" + vnf.getName());
		}

So the idea is to check if it is possible to use already existing token for query resources from OpenStack, so as I said now after installing this fixed version I did not get exception anymore but
I can't query resources, I will put the info from wireshark:

-------------------------------------------------------------------------
POST /v3/auth/tokens HTTP/1.1
Accept: application/json; charset=utf-8
OS4J-Auth-Command: Tokens
Content-Length: 303
Content-Type: application/json; charset=UTF-8
Host: x.x.x.x:5000
Connection: Keep-Alive
User-Agent: OpenStack4j-Agent
Accept-Encoding: gzip,deflate

{
  "auth" : {
    "identity" : {
      "token" : {
        "id" : "xxx"
      },
      "methods" : [ "token" ]
    }
  }
}HTTP/1.1 201 Created
Date: Wed, 19 Jul 2017 14:06:42 GMT
Server: Apache/2.4.10 (Ubuntu)
X-Subject-Token: xxx
Vary: X-Auth-Token
X-Distribution: Ubuntu
x-openstack-request-id: req-84ab892b-d9b9-443d-9d97-8eefec4e5e05
Content-Length: 343
Keep-Alive: timeout=5, max=99
Connection: Keep-Alive
Content-Type: application/json

{"token": {"issued_at": "2017-07-19T14:06:42.000000Z", "audit_ids": ["WmFpwxgcRSWYOpl4WBU8uA", "DfqgBG6USa2pvIuyW-yyRw"], "methods": ["token", "password"], "expires_at": "2017-07-19T15:06:42.232133Z", "user": {"domain": {"id": "xxx", "name": "xxx"}, "id": "xxx", "name": "xxx"}}}

GET /v1.0/vnfs HTTP/1.1
Accept: application/json; charset=utf-8
X-Auth-Token: xxx
User-Agent: OpenStack4j / OpenStack Client
Host: x.x.x.x:5000
Connection: Keep-Alive
Accept-Encoding: gzip,deflate

HTTP/1.1 404 Not Found
Date: Wed, 19 Jul 2017 14:06:42 GMT
Server: Apache/2.4.10 (Ubuntu)
Vary: X-Auth-Token
X-Distribution: Ubuntu
Content-Length: 93
Keep-Alive: timeout=5, max=98
Connection: Keep-Alive
Content-Type: application/json

{"error": {"message": "The resource could not be found.", "code": 404, "title": "Not Found"}}
-------------------------------------------------------------------------------------------------------------------

Looks like GET vnfs request goes to the wrong "Host" with 5000 port instead of 9890 (tacker API).

**Comment by auhlig** [comment]
The 2nd token has no scope, hence no service catalog and authorization.
```
{
	"token": {
		"issued_at": "2017-07-19T14:06:42.000000Z",
		"audit_ids": ["WmFpwxgcRSWYOpl4WBU8uA", "DfqgBG6USa2pvIuyW-yyRw"],
		"methods": ["token", "password"],
		"expires_at": "2017-07-19T15:06:42.232133Z",
		"user": {
			"domain": {
				"id": "xxx",
				"name": "xxx"
			},
			"id": "xxx",
			"name": "xxx"
		}
	}
}
```

**Comment by vkochan** [comment]
OK, but is there a some easy way in OpenStack4j to use existing token id w/o specifying a scope ( like putting the X-Auth-Token into HTTP header) to access OpenStack services ?

**Comment by auhlig** [comment]
This is unrelated from OpenStack4j. You always need to provide a scope in OpenStack to obtain a service catalog.

**Comment by vkochan** [comment]
So I am trying to figure out if it is possible to query OpenStack services via OpenStack4j by having only token id.

**Comment by auhlig** [comment]
You need to:
```java
OSClientV3 os2 = OSFactory.builderV3()
	                    .endpoint("http://x.x.x.x:5000/v3")
	                    .token(os.getToken().getId())
                            .scopeToProject(Identifier.byName("xxx"), Identifier.byName("xxx"))
	                    .authenticate();
```
Else please point out the keystone v3 API call, that answers an unscoped authentication with a scoped token containing the service catalog. I could not find it https://developer.openstack.org/api-ref/identity/v3/index.html#authentication-and-token-management

**Comment by auhlig** [comment]
That's easily possible and requires only another API call to Keystone to get more info on the token. But that discussion is out of context here, since it's not related to OpenStack4j anymore.

**Comment by vinodborole** [comment]
LGTM

**Pull request merged**
