### PR TITLE
Fix #856 - add @JsonProperty to NeutronLbPoolV2 sessionPersistance

### LINKED ISSUE #856: param 'sessionPersistence' of NeutronLbPoolV2 requires @JsonProperty
Hi Community，
     Param 'sessionPersistence' in class 'NeutronLbPoolV2' requires @JsonProperty or an error will be thrown.

ClientResponseException{message=Unrecognized attribute（s） 'sessionPersistence',，status=400， status-code=BAD_REQUEST}

### PR DESCRIPTION
**Pull request by emjburns**
@JerryShi this should fix the issue - let me know if it doesn't.
@vinodborole take a look please

### CODE REVIEW

**Comment by vinodborole** [comment]
LGTM, thanks a lot @emjburns appreciate your help :+1: 

@auhlig any thoughts?

**Comment by emjburns** [comment]
@vinodborole no problem! Please assign any tickets related to pieces I've contributed to me in the future - I'm happy to fix them :)

**Comment by auhlig** [comment]
Good to merge. Thanks for your commitment @emjburns.

**Comment by JerryShi** [comment]
@emjburns the same problem exists in 'NeutronLbPoolV2Update'. please fix it，too.  thx

**Pull request merged**
