### PR TITLE
aodh-gnocchi alarm  support

### PR DESCRIPTION
**Pull request by zizhongwei**
aodh-gnocchi alarm support
resolve issues:
#1126
#1108
#1103

### CODE REVIEW

**Comment by zizhongwei** [comment]
@auhlig Why does The Travis CI fail to start?

**Comment by vinodborole** [comment]
LGTM 👍

**Comment by PavanVadavi** [comment]
This has broken the master build.
@zizhongwei could you please fix or shall i revert this fix?

**Comment by PavanVadavi** [comment]
@vinodborole  and @auhlig  please take a look and could you please bring back master build to normalcy?

**Pull request merged**
