### PR TITLE
Dividing Builder-API by Identity version

### PR DESCRIPTION
**Pull request by auhlig**
As discussed in #666 this introduces the BuildersV2 and BuildersV3 to make it less likely to get confused by the 2 different Identity versions. 

What do you think @gondor , @dhague ?

### CODE REVIEW

**Comment by dhague** [comment]
As discussed with @auhlig via PM just now, this idea of using `Builders.<object>()` for everything except Identity, where we use `BuilderV2.<object>()` and `BuilderV3.<object>()` doesn't feel quite right.
A better approach would be to stay with `Builders.<object>()` which would always use the latest version of an API (and a point release of OS4J whenever this changes), together with `Builders.<service>().<object>()` when a specific version is required.
This would give, for example:
`Builders.user()` creating a V3 user (in the current 3.0 release of OS4J)
`Builders.identityV3().user()` creating a V3 user regardless of OS4J release (>3.0)
`Builders.identityV2().user()` creating a V2 user regardless of OS4J release (>3.0)

This same pattern can then be used to support different versions of the other OpenStack services, and has the advantage that users of OS4J v3.0 would not have a breaking change when using V3 user objects.

**Comment by gondor** [comment]
@auhlig @dhague I agree with the ```Builders.<service>.<object>``` approach.  I was thinking about it when I was getting ready for work and have V2 and V3 builders felt odd to me and would impose lots of breaking changes in the future.  I like rooting it to the service based on the version of the service being used.    Well promote less breaking changes.

**Comment by vinodborole** [comment]
Builders.<service>.<object> makes more sense

**Comment by gondor** [comment]
@auhlig @dhague - I know this is a PR :) But wanted to introduce @vinodborole who made a comment above.  He's been a big contributor as well.  Do you mind also reviewing his latest PR which is targeted for V3 - PR #671  .  @vinodborole - Darren and Arno did the V3 work, infact built the whole 3.0.0 release.

**Comment by vinodborole** [comment]
@gondor  Thanks for introducing me to the team; its a privilege working with you guyz. Let me know what you think about my PR;

**Comment by wumingcheng** [comment]
@auhlig when does the new version publish, two weaks has gone.And don't forget to amend the bug of #679,

**Comment by gondor** [comment]
Currently its done manually by me.  Working on integrating merged changes to deploy new snapshots via Travis CI.

**Comment by auhlig** [comment]
Hey @gondor, @dhague, @vinodborole,

**Comment by gondor** [comment]
LGTM - great job!

**Pull request merged**
