### PR TITLE
App catalog/Murano API support

### PR DESCRIPTION
**Pull request by nmakhotkin**
* Added Murano Service support to OSClient;
 * Added Murano Service to list of available APIs;
 * Implemented murano envronment API;
 * Added unit-tests for murano environments.

### CODE REVIEW

**Comment by nmakhotkin** [comment]
It partially fixes https://github.com/ContainX/openstack4j/issues/830

**Comment by auhlig** [comment]
Do you want to continue work on this PR, @nmakhotkin ?

**Comment by nmakhotkin** [comment]
@auhlig,

definitely yes, I plan to create a couple commits more.

**Comment by nmakhotkin** [comment]
I'm not sure if I do it correct. Is this acceptable if I send more than one commit in one pull request? If not, could you please explain the usual workflow for sending more than 1 commit in a chain?

**Comment by auhlig** [comment]
Either way is absolutely fine.
Just thought it might make sense to add a **WIP** to this PR and notify us when it's ready for review

**Comment by nmakhotkin** [comment]
Ok, thanks for the clarification. I just added **[WIP]** to the title of the PR.

**Comment by nmakhotkin** [comment]
Hi, @auhlig @vinodborole !

I just finished implementing basic Murano API functional. With this changes, user will be able to: 
 - create/delete environments
 - add/delete application(s) to the specified environment
 - deploy the environment

Note: I also tested all this functionality on our development OpenStack lab and it works fine.

PR is ready for review now.

P.S. The next plan is to improve existing murano API functionality: deployments API, packages API, categories API. These changes can be independent from each other and will contain only one commit in PR.

**Comment by gondor** [comment]
@nmakhotkin and team! Great work!  Quick pass I don't see anything that sticks out.  Thanks for adding all the tests to back your work.  LGTM.  @auhlig and @vinodborole i'll let you guys complete the review and merge if things look good.  I was recently in correspondence with this team (Mirantis) about adding this support to OpenStack4j in incremental stages so wanted to comment :)

**Comment by auhlig** [comment]
Thanks for sharing the info Jeremy.
I completely agree. Also after taking a closer look: Really nice work @nmakhotkin.

**Comment by nmakhotkin** [comment]
Thanks guys!

**Pull request merged**
