### PR TITLE
api added with server id as input

### PR DESCRIPTION
**Pull request by easyit**
Some of the existing API , such as addFloatingIP and removeFloatingIP  requires Server as parameter, which is heavy. Hence, here I create similar functions which take the server id as input:

Interface added in ComputeFloatingIPService.java
 `ActionResponse addFloatingIP(String serverId, String fixedIpAddress, String ipAddress);`

`ActionResponse addFloatingIP(String serverId, String ipAddress);`

`ActionResponse removeFloatingIP(String serverId, String ipAddress) ;`

[https://github.com/ContainX/openstack4j/issues/880](url)

### CODE REVIEW

**Comment by auhlig** [comment]
Hi @easyit,
Thanks for your work. Looks very good so far.
Could you add some tests for your additions?

**Comment by easyit** [comment]
@auhlig I cannot see any previous test cases regarding the ComputeFloatingIPService.

**Comment by auhlig** [comment]
@easyit What about https://github.com/ContainX/openstack4j/blob/master/core-test/src/main/java/org/openstack4j/api/compute/FloatingIPTests.java ?

**Comment by easyit** [comment]
@auhlig 

1. Testcase for floating Ip added
2. add bootable and encrypted property to volume model as mentioned in [issue 888 ](https://github.com/ContainX/openstack4j/issues/888)

**Comment by auhlig** [comment]
Good to merge @vinodborole ?

**Comment by vinodborole** [comment]
@easyit thanks for your work, looks good but i have few questions. What is the importance of following API  

ActionResponse addFloatingIP(String serverId, String fixedIpAddress, String ipAddress);

Also can you point me to its test case?

**Comment by easyit** [comment]
@vinodborole  `ActionResponse addFloatingIP(String serverId, String fixedIpAddress, String ipAddress)`  is corresponding to the existing API `ActionResponse  addFloatingIP(Server server, String fixedIpAddress, String ipAddress)`

**Comment by vinodborole** [comment]
Ok sounds good, can you please add a test case for that as well?

**Comment by easyit** [comment]
@gondor   Add some codes to support the volume backup feature, as mentioned in the issue below:  [https://github.com/ContainX/openstack4j/issues/874](url)

**Comment by auhlig** [comment]
Wow. Very cool @easyit. Thanks for the work. 

Just one thing: Could you revert the imports in `core/src/main/java/org/openstack4j/api/Builders.java` to stick to the pattern used before?

**Comment by easyit** [comment]
@auhlig  Finish reverting the the imports in` core/src/main/java/org/openstack4j/api/Builders.java`

**Comment by auhlig** [comment]
👍  Looks good from my side. Feel free to merge if you agree @vinodborole

**Comment by vinodborole** [comment]
@easyit i have added a comment on NetworkTests.java seems the test is failing, please correct it, thanks again!

**Comment by easyit** [comment]
@vinodborole  My mistake, forget to commit the networks_filtered.json.    Fix it now.

**Comment by vinodborole** [comment]
Thanks. LGTM

**Pull request merged**
