### PR TITLE
Mistral: adding workflow executions endpoint

### PR DESCRIPTION
**Pull request by rakhmerov**
* Made ActionResponse able to various 2xx HTTP codes, not only 200
    ** Added one more static method ActionResponse.actionSuccess() taking
      an integer code
    ** Fixed deletion tests for workflow, workbook and actions definitions
      to expect 204 code. 200 was expected due to aforementioned limitation
* Added an endpoint for Mistral workflow executions

### CODE REVIEW

**Comment by rakhmerov** [comment]
@vinodborole, @auhlig: Please review this PR when you have time. Thanks.

**Comment by vinodborole** [comment]
LGTM

**Comment by rakhmerov** [comment]
ok

**Comment by rakhmerov** [comment]
@auhlig Hi, can you please review it?

**Pull request merged**
