### PR TITLE
Wrong return type of disable/enable service actions

### PR DESCRIPTION
**Pull request by baseman79**
https://github.com/ContainX/openstack4j/issues/1044

### CODE REVIEW

**Comment by vinodborole** [comment]
@baseman79 I don't see a reason why the return type should not get parsed with Service class. It does satisfies all the parameters; can you share any exceptions or errors you get?

https://github.com/ContainX/openstack4j/blob/master/core/src/main/java/org/openstack4j/model/compute/ext/Service.java

**Comment by vinodborole** [comment]
@baseman79 I don't there would be need for this PR anymore; until there is something we are trying to fix here from the older code.

**Comment by baseman79** [comment]
@vinodborole 
` I don't see a reason why the return type should not get parsed with Service class. It does satisfies all the parameters; can you share any exceptions or errors you get?`

sorry, are you saying the old code with return type `Sevice.Status` will work fine?

**Comment by vinodborole** [comment]
@baseman79   Yes it should

**Comment by baseman79** [comment]
@vinodborole,

here is the return from OS:
```2017-08-08 10:00:05.148 [http-nio-127.0.0.1-8095-exec-5] INFO  os - 2 * Client response received on thread http-nio-127.0.0.1-8095-exec-5
2 < 200
2 < Connection: keep-alive
2 < Content-Length: 81
2 < Content-Type: application/json
2 < Date: Tue, 08 Aug 2017 14:00:10 GMT
2 < X-Compute-Request-Id: req-eacf5035-08c9-43dc-9b5c-74d5c88dbae0
{"service": {"status": "enabled", "binary": "nova-compute", "host": "somehost"}}
```

and the value I got back by using the old code

```
s	Service$Status  (id=81)	
	name	"UNRECOGNIZED" (id=87)	
	ordinal	2
```

**Comment by baseman79** [comment]
Hi @vinodborole, 

Just to be clear, I made a very simple call to disable a host with the current master code (return type is ```Service.Status```)
```
Service.Status s = oc.compute().services().disableService("nova-compute", hostName);
```
OS reponsed
```
2 < 200
2 < Connection: keep-alive
2 < Content-Length: 81
2 < Content-Type: application/json
2 < Date: Tue, 08 Aug 2017 14:00:10 GMT
2 < X-Compute-Request-Id: req-eacf5035-08c9-43dc-9b5c-74d5c88dbae0
{"service": {"status": "enabled", "binary": "nova-compute", "host": "somehost"}}
```
And I verified the host is disabled, but the return value I got for ```s```  is ```UNRECOGNIZED```

Do you still think this pr is not needed?

Thanks,

**Comment by vinodborole** [comment]
@baseman79 thank you for debuging this 

@auhlig what do you think?

**Comment by auhlig** [comment]
We're talking https://developer.openstack.org/api-ref/compute/#disable-scheduling-for-a-compute-service and https://developer.openstack.org/api-ref/compute/#enable-scheduling-for-a-compute-service, right? Both return a service, so this PR makes perfect sense.
It also looks like this is currently not tested, so I'd like to ask if you could add a unit test.

**Comment by baseman79** [comment]
@auhlig that's correct. I will add an unit test, thx

**Comment by baseman79** [comment]
@auhlig @vinodborole anyone?

**Comment by auhlig** [comment]
Sorry for the delay. I'll take a look in the evening.

**Comment by baseman79** [comment]
no worries, thanks @auhlig

**Comment by auhlig** [comment]
Thanks for contributing @baseman79

**Pull request merged**
